image:
  registry: public.ecr.aws
  repository: a6j2k0g1/event-forwarder
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0 # we currently use a hostPath as our state file.  This will move to something more robust as needed.
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

spyderbat:
  spyderbat_org_uid: your_org_uid # org uid to install into
  spyderbat_secret_api_key: your_api_key # api key
  api_host: api.prod.spyderbat.com # api host to use
  #matching_filters: [".*"]  # only write out events that match these regex filters (json/yaml array of strings syntax)
  #expr: # filter events using an expression syntax
  #webhook: # optional; default is no webhook
  #  endpoint_url: https://example.com/webhook # required for webhook
  #  compression_algo: zstd # optional [ zstd | gzip | default=none ]
  #  max_payload_bytes: 500000 # optional; default is 1048576 (1 MiB); max is 10485760 (10 MiB)
  #  authentication:
  #    method: bearer # [ bearer | basic | hmac | shared_secret | default=none ]
  #    parameters:
  #      header_name: X-HMAC # value required for hmac and shared_secret
  #      secret_key: base64-encoded-bearer-token # value required for bearer, hmac, and shared_secret
  #      hash_algo: sha256 # required for "hmac" authentication method; must be "sha256"
  #      username: username # value required for basic
  #      password: base64-encoded-password # value required for basic
