apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "event-forwarder.fullname" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    app: {{ template "event-forwarder.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
    config.yaml: |-
      # your spyderbat org UID goes here
      spyderbat_org_uid: {{ .Values.spyderbat.spyderbat_org_uid }}

      # your spyderbat API key goes here
      spyderbat_secret_api_key: {{ .Values.spyderbat.spyderbat_secret_api_key }}

      {{ if .Values.spyderbat.api_host }}
      # override the API endpoint (non-US regions only)
      api_host: {{ .Values.spyderbat.api_host }}

      {{ end }}
      # specify the location to write logs and keep state
      log_path: /opt/local/spyderbat/var/log

      stdout: true

      {{ if .Values.spyderbat.matching_filters }}
      matching_filters: {{- range .Values.spyderbat.matching_filters }}
        - {{.}}{{- end }}
      
      {{ end }}
      {{ if .Values.spyderbat.expr }}
      expr: |{{ .Values.spyderbat.expr | nindent 8 }}
      {{ end }}

      {{ if .Values.spyderbat.webhook }}
      webhook:
        endpoint_url: {{ .Values.spyderbat.webhook.endpoint_url }}
        {{ if .Values.spyderbat.webhook.insecure }}
        insecure: {{ .Values.spyderbat.webhook.insecure }}
        {{ end }}
        {{ if .Values.spyderbat.webhook.compression_algo }}
        compression_algo: {{ .Values.spyderbat.webhook.compression_algo }}
        {{ end }}
        {{ if .Values.spyderbat.webhook.max_payload_bytes }}
        max_payload_bytes: {{ .Values.spyderbat.webhook.max_payload_bytes }}
        {{ end }}
        {{ if .Values.spyderbat.webhook.authentication }}
        authentication:
          method: {{ .Values.spyderbat.webhook.authentication.method }}
          {{ if .Values.spyderbat.webhook.authentication.parameters }}
          parameters:
            {{ if .Values.spyderbat.webhook.authentication.parameters.header_name }}
            header_name: {{ .Values.spyderbat.webhook.authentication.parameters.header_name }}
            {{ end }}
            {{ if .Values.spyderbat.webhook.authentication.parameters.secret_key }}
            secret_key: {{ .Values.spyderbat.webhook.authentication.parameters.secret_key }}
            {{ end }}
            {{ if .Values.spyderbat.webhook.authentication.parameters.hash_algo }}
            hash_algo: {{ .Values.spyderbat.webhook.authentication.parameters.hash_algo }}
            {{ end }}
            {{ if .Values.spyderbat.webhook.authentication.parameters.username }}
            username: {{ .Values.spyderbat.webhook.authentication.parameters.username }}
            {{ end }}
            {{ if .Values.spyderbat.webhook.authentication.parameters.password }}
            password: {{ .Values.spyderbat.webhook.authentication.parameters.password }}
            {{ end }}
          {{ end }}
        {{ end }}
      {{ end }}
