apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-forwarder.fullname" . }}
  namespace: {{ .Values.spyderbat.namespace }}
  labels:
    {{- include "event-forwarder.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "event-forwarder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "event-forwarder.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - configMap:
          name: {{ include "event-forwarder.fullname" . }}
        name: config
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: /opt/local/spyderbat/config.yaml
            subPath: config.yaml
            readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
