apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "event-forwarder.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/sb-event-forwarder"