kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "event-forwarder.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "event-forwarder.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi