kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "event-forwarder.fullname" . }}-pvc
  namespace: {{ .Values.spyderbat.namespace }}
  labels:
    app: {{ include "event-forwarder.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi